// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TourPlanner.RestServer.DAL;

#nullable disable

namespace TourPlanner.RestServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TourPlanner.RestServer.Models.Tour", b =>
                {
                    b.Property<int>("TourId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TourId"));

                    b.Property<double>("Distance")
                        .HasColumnType("double precision");

                    b.Property<double>("EndLat")
                        .HasColumnType("double precision");

                    b.Property<string>("EndLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("EndLon")
                        .HasColumnType("double precision");

                    b.Property<float>("EstimatedTime")
                        .HasColumnType("real");

                    b.Property<double>("StartLat")
                        .HasColumnType("double precision");

                    b.Property<string>("StartLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("StartLon")
                        .HasColumnType("double precision");

                    b.Property<string>("TourDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TourName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TransportationType")
                        .HasColumnType("integer");

                    b.HasKey("TourId");

                    b.ToTable("Tours");
                });

            modelBuilder.Entity("TourPlanner.RestServer.Models.TourLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LogId"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<float>("DistanceTraveled")
                        .HasColumnType("real");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("TimeTaken")
                        .HasColumnType("real");

                    b.Property<int?>("TourId")
                        .HasColumnType("integer");

                    b.HasKey("LogId");

                    b.HasIndex("TourId");

                    b.ToTable("TourLogs");
                });

            modelBuilder.Entity("TourPlanner.RestServer.Models.TourLog", b =>
                {
                    b.HasOne("TourPlanner.RestServer.Models.Tour", null)
                        .WithMany("Logs")
                        .HasForeignKey("TourId");
                });

            modelBuilder.Entity("TourPlanner.RestServer.Models.Tour", b =>
                {
                    b.Navigation("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
