using Microsoft.EntityFrameworkCore;
using TourPlanner.RestServer.DAL.Repository.Interfaces;
using TourPlanner.RestServer.Models;

namespace TourPlanner.RestServer.DAL.Repository;

public class TourRepository : ITourRepository
{
    private readonly ITourLogRepository _tourLogRepository;
    private readonly AppDbContext _context;
    
    
    public TourRepository(AppDbContext context, ITourLogRepository tourLogRepository)
    {
        _context = context;
        _tourLogRepository = tourLogRepository;
    }

    
    public async Task<IEnumerable<Tour>> GetAllToursAsync()
    {
        var tours = await _context.Tours
            .Include(t => t.Logs)
            .ToListAsync();

        return tours;
    }

    
    public async Task<Tour> GetTourByIdAsync(int id)
    {
        var tour = await _context.Tours
            .Include(t => t.Logs)
            .FirstOrDefaultAsync(t => t.TourId == id);
        
        if (tour == null) 
        {
            throw new KeyNotFoundException($"Tour with ID {id} not found");
        }

        return tour;
    }

    
    public async Task<Tour> AddTourAsync(Tour newTour)
    {
        newTour.TourId = 0; // Clear any values in this field to ensure the ID will be auto-generated by the database
        
        _context.Tours.Add(newTour);
        await _context.SaveChangesAsync();
        
        return newTour; // The ID field is updated to the new auto-generated value automatically when calling SaveChangesAsync
    }

    
    public async Task<Tour> UpdateTourAsync(Tour updatedTour)
    { 
        // Retrieve the existing tour from the database, including its logs
        var tour = await _context.Tours
            .Include(t => t.Logs)
            .FirstOrDefaultAsync(t => t.TourId == updatedTour.TourId);
        
        if (tour == null)
        {
            throw new KeyNotFoundException($"Tour with ID {updatedTour.TourId} not found.");
        }

        // Update the tour's properties
        tour.TourName = updatedTour.TourName;
        tour.TourDescription = updatedTour.TourDescription;
        tour.StartLocation = updatedTour.StartLocation;
        tour.EndLocation = updatedTour.EndLocation;
        tour.TransportationType = updatedTour.TransportationType;
        tour.Distance = updatedTour.Distance;
        tour.EstimatedTime = updatedTour.EstimatedTime;
        
        tour.StartLat = updatedTour.StartLat;
        tour.StartLon = updatedTour.StartLon;
        tour.EndLat = updatedTour.EndLat;
        tour.EndLon = updatedTour.EndLon;

        // ------------------------------
        // Handle updating the TourLogs (simply doing tour.Logs = updatedTour.Logs; throws an exception)
        // ------------------------------

        // Remove logs that are no longer present in the updated tour
        var logsToRemove = tour.Logs
            .Where(existingLog => updatedTour.Logs.All(newLog => newLog.LogId != existingLog.LogId))
            .ToList();

        foreach (var log in logsToRemove)
        {
            await _tourLogRepository.DeleteTourLogAsync(log.LogId);
            
            // Remove the log from the local collection too (not necessary, but it doesn't hurt to ensure consistency)
            tour.Logs.Remove(log);
        }

        // Update all existing logs and add new logs
        foreach (var updatedLog in updatedTour.Logs)
        {
            // Check if the log already exists
            var existingLog = tour.Logs.FirstOrDefault(l => l.LogId == updatedLog.LogId);
            
            // Log already exists -> update it
            if (existingLog != null)
            {
                await _tourLogRepository.UpdateTourLogAsync(updatedLog);
            }
            // Log doesn't exist -> create it
            else
            {
                var addedLog = await _tourLogRepository.AddTourLogAsync(updatedTour.TourId, updatedLog);
                // Also add the new log to the local collection to ensure consistency
                tour.Logs.Add(updatedLog);
            }
        }

        // Save all changes.
        await _context.SaveChangesAsync();
        
        return tour;
    }

    
    public async Task<bool> DeleteTourAsync(int id)
    {
        var tour = await _context.Tours
            .Include(t => t.Logs)
            .FirstOrDefaultAsync(t => t.TourId == id);
        
        if (tour == null)
        {
            throw new KeyNotFoundException($"Tour with ID {id} not found.");
        }

        _context.Tours.Remove(tour);
        await _context.SaveChangesAsync();

        return true;
    }
}