using Microsoft.EntityFrameworkCore;
using TourPlanner.RestServer.DAL.Repository.Interfaces;
using TourPlanner.Model;

namespace TourPlanner.RestServer.DAL.Repository;

public class TourLogRepository : ITourLogRepository
{
    private readonly AppDbContext _context;
    
    
    public TourLogRepository(AppDbContext context)
    {
        _context = context;
    }
    
    
    /// <summary>
    /// Retrieves a TourLog by its ID
    /// </summary>
    /// <param name="id">The ID of the TourLog to retrieve</param>
    /// <returns>The <see cref="TourLog"/> with the specified ID</returns>
    /// <exception cref="KeyNotFoundException">Thrown if no TourLog with the specified ID exists</exception>
    public async Task<TourLog> GetTourLogByIdAsync(int id)
    {
        var log = await _context.TourLogs.FirstOrDefaultAsync(l => l.LogId == id);
        
        if (log == null)
        {
            throw new KeyNotFoundException($"TourLog with ID {id} not found");
        }
        
        return log;
    }


    /// <summary>
    /// Adds a new TourLog to the specified tour
    /// </summary>
    /// <param name="parentTourId">The ID of the tour to which the new TourLog should be added</param>
    /// <param name="newLog">The TourLog object to add</param>
    /// <returns>The newly added <see cref="TourLog"/> object, including its auto-generated ID</returns>
    /// <exception cref="KeyNotFoundException">Thrown if no tour with the specified ID exists</exception>
    public async Task<TourLog> AddTourLogAsync(int parentTourId, TourLog newLog)
    {
        var tour = await _context.Tours
            .Include(t => t.Logs)
            .FirstOrDefaultAsync(t => t.TourId == parentTourId);
        
        if (tour == null)
        {
            throw new KeyNotFoundException($"Tour with ID {parentTourId} not found");
        }

        newLog.LogId = 0; // Clear any values in this field to ensure the ID will be auto-generated by the database
        
        tour.Logs.Add(newLog);
        await _context.SaveChangesAsync();
        
        return newLog; // The ID field is updated to the new auto-generated value automatically when calling SaveChangesAsync
    }


    /// <summary>
    /// Updates an existing TourLog with new details.
    /// </summary>
    /// <param name="updatedTourLog">The TourLog object containing updated information</param>
    /// <returns>The updated <see cref="TourLog"/> object</returns>
    /// <exception cref="KeyNotFoundException">Thrown if no TourLog with the specified ID exists</exception>
    public async Task<TourLog> UpdateTourLogAsync(TourLog updatedTourLog)
    {
        var log = await _context.TourLogs.FirstOrDefaultAsync(l => l.LogId == updatedTourLog.LogId);
        if (log == null)
        {
            throw new KeyNotFoundException($"TourLog with ID {updatedTourLog.LogId} not found");
        }

        // Update log properties
        log.Comment = updatedTourLog.Comment;
        log.Difficulty = updatedTourLog.Difficulty;
        log.DistanceTraveled = updatedTourLog.DistanceTraveled;
        log.TimeTaken = updatedTourLog.TimeTaken;
        log.Rating = updatedTourLog.Rating;
        log.TimeStamp = updatedTourLog.TimeStamp;

        await _context.SaveChangesAsync();
        
        return log;
    }


    /// <summary>
    /// Deletes a TourLog by its ID
    /// </summary>
    /// <param name="id">The ID of the TourLog to delete</param>
    /// <returns>A boolean indicating whether the deletion was successful</returns>
    /// <exception cref="KeyNotFoundException">Thrown if no TourLog with the specified ID exists</exception>
    public async Task<bool> DeleteTourLogAsync(int id)
    {
        var log = await _context.TourLogs.FirstOrDefaultAsync(l => l.LogId == id);
        
        if (log == null)
        {
            throw new KeyNotFoundException($"TourLog with ID {id} not found");
        }

        _context.TourLogs.Remove(log);
        await _context.SaveChangesAsync();
        
        return true;
    }
}